spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ProjectDatabase
    username: root
    password: password
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      globally_quoted_identifiers: true
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:exercisedb
    driverClassName: org.h2.Driver
    username: testdb
    password: psw1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enable: true
server:
  port: 3000